import type { Metadata } from 'next'

import './globals.css'
import { Providers } from './Providers'

export const metadata: Metadata = {
    title: 'CloudStore',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full w-full">
            <body className="w-full h-full">
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
