import type { Metadata } from "next";

import "./globals.css";
import QueryProvider from "./queryProvider";

export const metadata: Metadata = {
  title: "CloudStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="w-full h-full">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
